/*
 * CREATE TABLESPACE DMT_TBS DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/DMT.dbf' SIZE 50m AUTOEXTEND ON;
 * 
 * CREATE USER DMT IDENTIFIED BY DMT DEFAULT TABLESPACE DMT_TBS;
 * 
 * GRANT CONNECT TO DMT;
 * 
 * GRANT RESOURCE TO DMT;
 * 
 * 
*/

Insert into CLIENT (CLIENT_ID,CLIENT_NAME) values (200,'PIF');
Insert into CLIENT (CLIENT_ID,CLIENT_NAME) values (201,'LIG');
Insert into CLIENT (CLIENT_ID,CLIENT_NAME) values (202,'Fidelity');

Insert into PRODUCT (PRODUCT_ID,PRODUCT_NAME) values (100,'InvestOne');
Insert into PRODUCT (PRODUCT_ID,PRODUCT_NAME) values (101,'Investran');
Insert into PRODUCT (PRODUCT_ID,PRODUCT_NAME) values (102,'IntelliMatch');

Insert into MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (300,100,'Account');
Insert into MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (301,100,'Security');
Insert into MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (303,100,'Trade');

Insert into FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (400,300,'ACCT','Account Number');
Insert into FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (401,300,'ACCDT','Account Date');

Insert into LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (500,202,100);
Insert into LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (501,202,102);

Insert into MAPPING (CLI_PRO_ID,MODULE_ID,FIELD_ID,FIELD_VALUE) values (500,300,400,'Account Number');

Insert into DMT1.CLIENT (CLIENT_ID,CLIENT_NAME) values (200,'PIF');
Insert into DMT1.CLIENT (CLIENT_ID,CLIENT_NAME) values (201,'LIG');
Insert into DMT1.CLIENT (CLIENT_ID,CLIENT_NAME) values (202,'Fidelity');
Insert into DMT1.CLIENT (CLIENT_ID,CLIENT_NAME) values (203,'WR');
Insert into DMT1.CLIENT (CLIENT_ID,CLIENT_NAME) values (204,'LFS');

Insert into DMT1.PRODUCT (PRODUCT_ID,PRODUCT_NAME) values (100,'InvestOne');
Insert into DMT1.PRODUCT (PRODUCT_ID,PRODUCT_NAME) values (101,'Investran');
Insert into DMT1.PRODUCT (PRODUCT_ID,PRODUCT_NAME) values (102,'IntelliMatch');
Insert into DMT1.PRODUCT (PRODUCT_ID,PRODUCT_NAME) values (103,'Front Arena');
Insert into DMT1.PRODUCT (PRODUCT_ID,PRODUCT_NAME) values (104,'Adaptive');

Insert into DMT1.LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (500,202,100);
Insert into DMT1.LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (501,202,102);
Insert into DMT1.LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (502,200,102);
Insert into DMT1.LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (503,201,100);
Insert into DMT1.LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (504,201,103);
Insert into DMT1.LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (505,201,102);
Insert into DMT1.LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (506,202,103);
Insert into DMT1.LK_CLIENT_PRODUCT (CLI_PRO_ID,CLIENT_ID,PRODUCT_ID) values (507,202,104);

Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (300,100,'Account');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (301,100,'Security');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (303,100,'Trade');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (304,100,'Rates');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (305,100,'Prices');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (302,100,'Rates');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (402,101,'Rates');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (400,101,'Account');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (401,101,'Security');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (403,101,'Trade');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (404,101,'Prices');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (500,102,'Account');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (501,102,'Security');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (503,102,'Trade');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (504,102,'Prices');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (502,102,'Rates');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (600,103,'Account');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (601,103,'Security');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (603,103,'Trade');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (604,103,'Prices');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (602,103,'Rates');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (700,104,'Account');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (701,104,'Security');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (703,104,'Trade');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (704,104,'Prices');
Insert into DMT1.MODULE (MODULE_ID,PRODUCT_ID,MODULE_NAME) values (702,104,'Rates');

Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (400,300,'AN','Account Number');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (401,300,'DT','Account Date');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (402,300,'AC','Account Class');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (403,300,'NV','NAV');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (404,300,'EQ','Shareholder Equity');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (405,300,'SO','Outstanding Shares/Par');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (406,300,'UT','Dividend Earning Shares');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (407,300,'TS','Subscriptions');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (408,300,'ES','Subscriptions Exchanged');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (409,300,'RI','Dividends Reinvested');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (410,300,'TR','Redemptions');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (500,300,'AN','Account Number');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (501,300,'DT','Valuation Period-End Date');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (502,300,'AC','Account Class');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (503,300,'NV','NAV');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (504,300,'EQ','Shareholder Equity');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (505,300,'SO','Outstanding Shares/Par');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (506,300,'UT','Dividend Earning Shares');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (507,300,'TS','Subscriptions');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (508,300,'ES','Subscriptions Exchanged');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (509,300,'RI','Dividends Reinvested');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (600,300,'AN','Account Number');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (601,300,'DT','Valuation Period-End Date');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (602,300,'AC','Account Class');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (603,300,'NV','NAV');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (604,300,'EQ','Shareholder Equity');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (605,300,'SO','Outstanding Shares/Par');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (606,300,'UT','Dividend Earning Shares');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (607,300,'TS','Subscriptions');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (608,300,'ES','Subscriptions Exchanged');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (609,300,'RI','Dividends Reinvested');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (700,300,'AN','Account Number');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (701,300,'DT','Valuation Period-End Date');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (702,300,'AC','Account Class');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (703,300,'NV','NAV');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (704,300,'EQ','Shareholder Equity');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (705,300,'SO','Outstanding Shares/Par');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (706,300,'UT','Dividend Earning Shares');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (707,300,'TS','Subscriptions');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (708,300,'ES','Subscriptions Exchanged');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (709,300,'RI','Dividends Reinvested');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (411,301,'AN','Account Number');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (412,301,'CU','Security Number');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (413,301,'SD','Security Description (Short)');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (414,301,'RES','HL Restriction Carry');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (415,301,'LQ','Taxlot Shares/Par');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (416,301,'TD','Taxlot Cost (Base)');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (417,301,'AG','Asset Group');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (418,301,'4e','Security ISIN');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (419,301,'CV','Shares/Par');
Insert into DMT1.FIELDS (FIELD_ID,MODULE_ID,FIELD_NAME,FIELD_DESC) values (420,301,'AI','Accrued Income Gross');

